### ISSUE TITLE
How to load multiple config files?

### ISSUE THREAD

**Issue by breezewish** [Wheellllll/ConfigManager#1]
The following code doesn't work.

``` java
Config.setConfigName(...);
Config cfg1 = Config.getConfig();
Config.setConfigName(...);
Config cfg2 = Config.getConfig();
```

And your interface is forcing me to use "procedural programming" instead of "OOP" in Java, which is horrible:

```
setXXX();
xxx = doXXX();
setXXX();
xxx = doXXX();
```

You are just adding `Config.` prefix to those procedural interfaces.

**Comment by blackbbc** [comment]
We do not provide this feature because config is a single instance

**Comment by breezewish** [comment]
How can you confidently say that config is a single instance :P

Take a look at hadoop, hive, elasticsearch, etc. Non of these have only one config file.
